apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  GITHUB_WEBHOOK_SECRET: "myWebhook_@#12323443"
  GITHUB_APP_ID:  "4148262"
  GITHUB_APP_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAtYcn5+TmyygMWoloUB3QoEaojWRAju9HOdUZXekCNgybO5uk
    mh3XgqVZSp/isQedtEYJkzjDClBs9Z+JYwDrlC8o1Dg7Gs2JCyH7DHtBj5v6/p83
    /kO5AmXaHsf3ScRuCd0GB/zfNtZ9uneDkKLu/fLY+ArYgr4bNt2POS6fMHnuXMaw
    djtdY41Z1ju9pBciw1z4Y4qj9ti0BxECOoHXeP5/uGGEkxM6UAfYSW9vTYzw/scF
    Tjl2zRfCGJcsAJfJjPQrrumygn7QX6RYV1Emhj/uML7AKlMMHd4kQ2o4XOkDyxdq
    KTpXhrPIEgxOUuCJ/j7tBEOrtXAzl81X7jKR4QIDAQABAoIBACpEmkooxoSvgpDi
    RePBzX5EdaLWoSGnHZKdyBZR1y32qX6rsxwfrrrA/ZWevQ4zk8kSNdCN+vw/1d8r
    krX21OPgR0WDAmAvU6W/99DkMlPaIgt/z23pHv8r8CoSrcYDcwvg5zKc8uy17Piq
    M3xONA/1qAe5nshys6uG036hGHgUx4NSG72yblRk51oou/nUQWIuySpaHFP22Hfl
    r5iZOdtvLytB6qk/5iqGjbF1w9X5ZXlrWXoPech8kpV+Y2DdkSCivCLxrGKbzlKx
    /caH5LVU/qGQJSGd0XT7q0IwtA+B45Wml4Huo3VahTVO2uSnxOIyz4pdJ+qOKw6J
    3WaRZ0ECgYEA52AhkRZcHlx19HeotJHvuW3MUqYxNL4DLDF2XYQ7o/VZbaCPiWR8
    D4OigtrA9/mlw36s5cDChHQ+dqxQhBWJ3IJbH7nozNIwIib7uAOd/0bmAvFRGDiP
    TUyaPrqaAmm5b30+lQgi1zGDeDWMUpfy3+9pNC2fED2uziAP0/+oGaUCgYEAyNjr
    McOeW0xJulaWbAFw+FurKgx6AHdjcoQ9Ct9T6o/F6GF7UX26zxgkxsUetWckHfPG
    VFbkuw3r9woFJfN+W6h+qXzsxwSE4nP5E1VqoIzTx5KoQmMewNnEuzpes24WOrqE
    qk70YgCJt86+Himaw/53er97CC4szVUIRQxsCo0CgYEA13wkRue4K16ZTHEU4fb4
    eI3VuTOmqCQ++C2ouzeoA+9AtmTOyXqYQCqsc4ogJdKPmx6jD+cSQiGw+v1Ij3sv
    xfpxu359XiRzR5te2+Yig9kX5q2whQpIDAnHrZxESvMEDN1sJ4hISnqGorHcWh/B
    xuVF6Z6DgbCw2K/rjdmQSTECgYEAxlvdpM9S1U45vouHkfG2dcJrAGNEFrPShqXt
    d5Bq20zVI5Uq6qem2KM6pwjFNFlCBUbdyCvtSIQOWHQP85RQZgu51IAphMCE0PXC
    t4JzhU6wVfkUrkQgekxYjKSwJLuDvsq4/U5u818epGbNwxJJ5Gmr7JGx27lmy/+/
    5BnJln0CgYEAsMhxfQXZQG/EdA/a3HIgx90KIOhbU0RS0GNs4xlxifBiMk1weRmq
    2Ilvcvaamith6ci3LP9pufU1hv/0FX1Nq1mgJ2waOOQP1/cBUxKdBN3x3iL7vF4u
    oagEB+ZcEYTWE82AiBvmR4RoWpAT4HwbGsgF2qzg06iZmmGV/QPkf74=
    -----END RSA PRIVATE KEY-----

  OPENAI_API_KEY: ""
  LANGFUSE_PUBLIC_KEY: "pk-lf-0b00d726-bb0c-457d-8080-185410424f7d"
  LANGFUSE_SECRET_KEY: "sk-lf-6f4af703-7e87-470f-8c4a-2efa003553b8"
  DATABASE_URL: "postgresql+asyncpg://dbadmin:YourStrongPassword123!@ai-code-reviewer-postgres.cra22scqu5da.eu-north-1.rds.amazonaws.com/codereviewer"